name: Debug

on:
  push:
    branches:
      - '**'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24.1

    - name: Build
      run: go mod tidy && go build -v ./...